"""
Answer file generation utilities.

Handles collecting user responses and writing the answers file.
"""

from dataclasses import dataclass
from pathlib import Path

from agentkit.parser import PromptDefinition
from agentkit.templates import get_output_dir


@dataclass
class PromptAnswer:
    """Represents a user's answer to a prompt question."""

    id: str
    user_response: str
    format: str = "text"


def format_answer_block(answer: PromptAnswer) -> str:
    """
    Format a single answer into the {{ANSWER: ...}} block syntax.

    Args:
        answer: The PromptAnswer to format

    Returns:
        Formatted answer block string
    """
    # AIDEV-NOTE: Always use YAML literal block syntax for consistency
    # Indent each line of the response for readability
    indented_lines = "\n".join(
        f"    {line}" for line in answer.user_response.split("\n")
    )
    return f"""{{{{ANSWER: {answer.id}
  user_response: |
{indented_lines}
}}}}"""


def generate_answers_content(answers: list[PromptAnswer]) -> str:
    """
    Generate the full answers file content.

    Args:
        answers: List of all prompt answers

    Returns:
        Complete markdown file content
    """
    lines = [
        "# Template Answers",
        "",
        "<!-- Generated by Agent Agent Kit -->",
        "<!-- Use these answers with the template to generate your agent file -->",
        "",
    ]

    for answer in answers:
        lines.append(format_answer_block(answer))
        lines.append("")

    return "\n".join(lines)


def write_answers_file(
    template_name: str,
    answers: list[PromptAnswer],
    output_dir: Path | None = None,
) -> Path:
    """
    Write the answers to a markdown file.

    Args:
        template_name: Name of the template (used for filename)
        answers: List of all prompt answers
        output_dir: Directory for output (defaults to ./output)

    Returns:
        Path to the created file
    """
    if output_dir is None:
        output_dir = get_output_dir()

    filename = f"{template_name}.answers.md"
    output_path = output_dir / filename

    content = generate_answers_content(answers)
    output_path.write_text(content, encoding="utf-8")

    return output_path


def collect_answer(prompt: PromptDefinition, response: str) -> PromptAnswer:
    """
    Create a PromptAnswer from a prompt definition and user response.

    Args:
        prompt: The prompt definition
        response: The user's response (may be empty if default used)

    Returns:
        PromptAnswer with the appropriate value
    """
    # Use default if response is empty and default exists
    if response.strip():
        final_response = response
    else:
        # AIDEV-NOTE: Unescape \n in defaults to convert to actual newlines
        default_value = prompt.default or ""
        final_response = default_value.replace("\\n", "\n")

    return PromptAnswer(
        id=prompt.id, user_response=final_response, format=prompt.format
    )
